name: Run test and publish to NPM

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test
        
  version-bump:
    needs: build
    runs-on: ubuntu-latest
    name: Automated Version Bump
    steps:
      - uses: phips28/gh-action-bump-version@v5.0.12
  
  publish-npm:
    needs: version-bump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
